version: '2'

services:
  sources:
      image: busybox
      volumes:
          - /home/docker/data/docker:/var/www
  data:
      image: busybox
      volumes:
          - /var/www/var/cache
          - /var/www/var/logs
          - /data/db

  elasticsearch:
      build:
        context: ./docker/elasticsearch
      volumes:
        - ${HOME_DIR}/data/elasticsearch:/usr/share/elasticsearch/data

  redis:
      image: redis:3.2
      volumes_from:
          - data

  db:
      image: mariadb:10.0
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=flexishore
          - MYSQL_PASSWORD=flexishore
          - MYSQL_DATABASE=flexishore
      volumes:
          - ${HOME_DIR}/data:/docker-entrypoint-initdb.d
          - ${HOME_DIR}/data/mysql:/var/lib/mysql
      volumes_from:
          - data
      ports:
          - "3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
          - db
      ports:
          - "8080:80"

  phpfpm:
    build:
      context: ./docker/phpfpm
    volumes:
      - ${HOME_DIR}/src:/usr/src/myapp
    links:
      - redis

  nginx:
    image: nginx:1.11
    links:
      - phpfpm:docker
      - db
      - redis
      -elasticsearch
    volumes:
      - ${HOME_DIR}/docker/vhost.conf:/etc/nginx/conf.d/app.conf.template
      - ${HOME_DIR}/src:/usr/src/myapp
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"